defaults:
  - writer: cometml
  - metrics: example
  - datasets: example
  - dataloader: example
  - transforms: example_only_batch
  - _self_
model:
  _target_: src.model.SoundStreamModel
  in_channels: 1
  base_channels: 32
  latent_dim: 128
  strides: [2, 4, 5, 5]
  num_quantizers: 8
  codebook_size: 1024
discriminator:
  _target_: src.model.SoundStreamDiscriminator
optimizer_g:
  _target_: torch.optim.Adam
  lr: 2e-4
  betas: [0.5, 0.9]
optimizer_d:
  _target_: torch.optim.Adam
  lr: 2e-4
  betas: [0.5, 0.9]
loss_function_g:
  _target_: src.loss.GeneratorLoss
  lambda_adv: 1.0
  lambda_feat: 100.0
  lambda_rec: 1.0
loss_function_d:
  _target_: src.loss.DiscriminatorLoss
trainer:
  log_step: 100
  n_epochs: 100
  epoch_len: 450
  device_tensors: ["audio"] # which tensors should be on device (ex. GPU)
  resume_from: null # null or path to the checkpoint dir with *.pth and config.yaml
  device: auto # device name or "auto"
  override: True # if True, will override the previous run with the same name
  monitor: "off" # "off" or "max/min metric_name", i.e. our goal is to maximize/minimize metric
  save_period: 5 # checkpoint each save_period epochs in addition to the best epoch
  early_stop: ${trainer.n_epochs} # epochs for early stopping
  save_dir: "saved"
  seed: 1
