defaults:
  - model: soundstream
  - metrics: soundstream
  - datasets: librispeech
  - dataloader: inference
  - transforms: soundstream
  - _self_
inferencer:
  device_tensors: ["audio"] # which tensors should be on device (ex. GPU)
  device: auto # device name or "auto"
  save_path: "test_results" # any name here, can be a dataset name
  seed: 1
  from_pretrained: "saved/soundstream_full_train/checkpoint-epoch100.pth" # path to the pretrained model
trainer:
  device: ${inferencer.device}
